spring:

  # jpa properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    #database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    generate-ddl: true